### PR TITLE
Local code mapping

### PR DESCRIPTION
**Pull request by c-schuler**
Replacement PR for #14

### CODE REVIEW

**Comment by c-schuler** [comment]
@MikeRileyGTRI 

Thank you very much for the contribution. I have reviewed this logic and made several changes. I am very happy with this as a naive implementation, but I do worry the logic is incomplete. My main concern involves the expression iteration to identify a ConceptEvaluator expression. 

Please review my changes and, if you approve, I will merge.

**Comment by MikeRileyGTRI** [comment]
Hey c-schuler. These changes look great. I'm not too good at parsing the library code, so my original call was just to pull the conceptevaluators that I put at the top of the file. I wasn't thinking about handling every possible expression. I just wanted to capture my conceptEvaluators that define my code sets. I think these are semantically the same thing, but that was my original intent.


Michael Riley
Research Scientist 1
Information and Communications Lab
Georgia Tech Research Institute
Atlanta, GA

Michael.Riley@gtri.gatech.edu<mailto:Michael.Riley@gtri.gatech.edu>
Phone 404 407-6920



________________________________

**Comment by c-schuler** [comment]
I think that is fine as long as we document the limitations. I will create an issue to track that.

Thanks again!

**Comment by c-schuler** [comment]
See #18

**Pull request merged**
